#docker_compose yaml
version: '3.9'
services:
  database_pg:
    image: postgres
    container_name: database_pg
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file:
      - database.env

  app:
    build: .
    container_name: app
    depends_on:
      - database_pg
    env_file:
      - database.env
    environment:
      - POSTGRES_HOST=database_pg

volumes:
  database-data:
    driver: local
